server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone:
        ${EUREKA_SERVER:http://eurekaservice:8761/eureka}

  instance:
    appname: api-gateway-service
    instanceId: api-gateway-service

spring:
  application:
    name: api-gateway-service
  cloud:
    loadbalancer:
      cache:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            max-age: 3600
            allowed-headers: "Requestor-Type"
            exposed-headers: "X-Get-Header"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat-service/**

        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/music-service/**