spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: discovery-service
          uri: lb://discovery-service
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat-service/**

          # PER ACCEDERE, DA BROWSER ANDARE SU: http://localhost:8080/DEMO1/say

  application:
    name: api-gateway-service
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}