version: "3"

services:

  #######################################
  # MYSQL DBMS
  #######################################

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

    #######################################
    # PHP MY ADMIN
    #######################################

  phpmyadmin:
    image: phpmyadmin
    links:
      - db:db
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

volumes:
  persistent:

# PER ACCEDERE A MYSQL DA PHPMYADMIN:
# Username:   root
# Password:   test
