version: "3"

services:

  #######################################
  # MYSQL DBMS
  #######################################

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: prova
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

    #######################################
    # PHP MY ADMIN
    #######################################

  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      PMA_HOST: mysql
volumes:
  persistent:

# PER ACCEDERE A MYSQL DA PHPMYADMIN:

# sudo docker-compose -f docker-compose.yml up --force-recreate -V
# localhost:80
# Username:   root
# Password:   test


# Se non si riescono a chiudere i container
# sudo systemctl stop docker.socket
# sudo systemctl stop docker
# sudo systemctl restart docker
