version: '3.7'

services:

  mysqlAuthDB:
    image: mysql:8.0
    container_name: mysqlAuthDB
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AuthDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - mysqldataauth:/var/lib/mysql
    restart: always
    networks:
      - mynetwork


  #######################################
  # auth-service container
  #######################################

  auth-service:
    container_name: auth-service
    build:
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - "8090:8090"
    networks:
      - mynetwork
    restart: always


volumes:
  mysqldataauth:

networks:
  mynetwork:
    driver: bridge